kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: worker-user-data
  type: Opaque
  files:
    - userData=worker-user-data.sh
- name: master-user-data
  type: Opaque
  commands:
    - userData=master-user-data.sh

namespace: openstack-provider-system
