# Please see the documentation for all configuration options: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
## main branch config starts here
# github-actions
- directory: "/"
  package-ecosystem: "github-actions"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: main
  groups:
    all-github-actions:
      patterns: ["*"]
  commit-message:
    prefix: ":seedling:"
    include: scope
  labels:
  - "area/dependency"
  - "ok-to-test"
# Go directories
- directories:
  - "/"
  - "/hack/tools"
  package-ecosystem: "gomod"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: main
  groups:
    all-go-mod-patch-and-minor:
      patterns: ["*"]
      update-types: ["patch", "minor"]
  commit-message:
    prefix: ":seedling:"
    include: scope
  ignore:
  # Ignore controller-runtime major and minor bumps as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore k8s major and minor bumps and its transitives modules
  - dependency-name: "k8s.io/*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - dependency-name: "sigs.k8s.io/controller-tools"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
  - "area/dependency"
  - "ok-to-test"
## main branch config ends here
## release-0.14 branch config starts here
# github-actions
- directory: "/"
  package-ecosystem: "github-actions"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: release-0.14
  groups:
    all-github-actions:
      patterns: ["*"]
  commit-message:
    prefix: ":seedling:"
    include: scope
  labels:
  - "area/dependency"
  - "ok-to-test"
# Go directories
- directories:
  - "/"
  - "/hack/tools"
  package-ecosystem: "gomod"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: release-0.14
  groups:
    all-go-mod-patch-and-minor:
      patterns: ["*"]
      update-types: ["patch", "minor"]
  commit-message:
    prefix: ":seedling:"
    include: scope
  ignore:
  # Ignore CAPI major and minor bumps
  - dependency-name: "sigs.k8s.io/cluster-api*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore controller-runtime major and minor bumps as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore k8s major and minor bumps and its transitives modules
  - dependency-name: "k8s.io/*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - dependency-name: "sigs.k8s.io/controller-tools"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
  - "area/dependency"
  - "ok-to-test"
## release-0.14 branch config ends here
## release-0.13 branch config starts here
# github-actions
- directory: "/"
  package-ecosystem: "github-actions"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: release-0.13
  groups:
    all-github-actions:
      patterns: ["*"]
  commit-message:
    prefix: ":seedling:"
    include: scope
  labels:
  - "area/dependency"
  - "ok-to-test"
# Go directories
- directories:
  - "/"
  - "/hack/tools"
  package-ecosystem: "gomod"
  schedule:
    interval: "weekly"
    day: "monday"
  target-branch: release-0.13
  groups:
    all-go-mod-patch-and-minor:
      patterns: ["*"]
      update-types: ["patch", "minor"]
  commit-message:
    prefix: ":seedling:"
    include: scope
  ignore:
  # Ignore CAPI major and minor bumps
  - dependency-name: "sigs.k8s.io/cluster-api*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore controller-runtime major and minor bumps as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore k8s major and minor bumps and its transitives modules
  - dependency-name: "k8s.io/*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - dependency-name: "sigs.k8s.io/controller-tools"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Ignore ORC major and minor bumps to prevent cascading k8s.io and controller-runtime updates
  - dependency-name: "github.com/k-orc/openstack-resource-controller*"
    update-types: ["version-update:semver-major", "version-update:semver-minor"]
  labels:
  - "area/dependency"
  - "ok-to-test"
## release-0.13 branch config ends here
