# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
  "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
  "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
  "sigs.k8s.io/controller-runtime/pkg/client/config",
  "sigs.k8s.io/controller-runtime/pkg/controller",
  "sigs.k8s.io/controller-runtime/pkg/handler",
  "sigs.k8s.io/controller-runtime/pkg/manager",
  "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
  "sigs.k8s.io/controller-runtime/pkg/source",
  "sigs.k8s.io/testing_frameworks/integration", # for integration testing
  "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
]

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"


[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "github.com/openshift/cluster-api"
  branch = "openshift-4.2-cluster-api-0.0.0-alpha.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.10"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

[[override]]
  name = "k8s.io/cluster-bootstrap"
  revision = "c9acc0c1bea2de07a6d31502c2fece9139c7f793"

[[constraint]]
  name = "github.com/gophercloud/utils"
  revision = "9c3b9f2457ef7011d3a20c9964e5d7107e9ed33c"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"


[[constraint]]
  name = "k8s.io/klog"
  version = "0.1.0"

[[constraint]]
  name = "sigs.k8s.io/yaml"
  version = "1.1.0"

[[override]]
  name = "github.com/ajeddeloh/yaml"
  revision = "6b94386aeefd8c4b8470aee72bfca084c2f91da9"


[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/apimachinery"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/openshift/cluster-api"
  unused-packages = false
  non-go = false
