apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: openstackclusterproviderstatuses.openstackproviderconfig.openshift.io
spec:
  group: openstackproviderconfig.openshift.io
  names:
    kind: OpenstackClusterProviderStatus
    plural: openstackclusterproviderstatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        controlPlaneSecurityGroup:
          description: 'ControlPlaneSecurityGroups contains all the information about
            the OpenStack Security Group that needs to be applied to control plane
            nodes. TODO: Maybe instead of two properties, we add a property to the
            group?'
          properties:
            id:
              type: string
            name:
              type: string
            rules:
              items:
                properties:
                  direction:
                    type: string
                  etherType:
                    type: string
                  name:
                    type: string
                  portRangeMax:
                    format: int64
                    type: integer
                  portRangeMin:
                    format: int64
                    type: integer
                  protocol:
                    type: string
                  remoteGroupID:
                    type: string
                  remoteIPPrefix:
                    type: string
                  securityGroupID:
                    type: string
                required:
                - name
                - direction
                - etherType
                - securityGroupID
                - portRangeMin
                - portRangeMax
                - protocol
                - remoteGroupID
                - remoteIPPrefix
                type: object
              type: array
          required:
          - name
          - id
          - rules
          type: object
        globalSecurityGroup:
          description: GlobalSecurityGroup contains all the information about the
            OpenStack Security Group that needs to be applied to all nodes, both control
            plane and worker nodes.
          properties:
            id:
              type: string
            name:
              type: string
            rules:
              items:
                properties:
                  direction:
                    type: string
                  etherType:
                    type: string
                  name:
                    type: string
                  portRangeMax:
                    format: int64
                    type: integer
                  portRangeMin:
                    format: int64
                    type: integer
                  protocol:
                    type: string
                  remoteGroupID:
                    type: string
                  remoteIPPrefix:
                    type: string
                  securityGroupID:
                    type: string
                required:
                - name
                - direction
                - etherType
                - securityGroupID
                - portRangeMin
                - portRangeMax
                - protocol
                - remoteGroupID
                - remoteIPPrefix
                type: object
              type: array
          required:
          - name
          - id
          - rules
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        network:
          description: Network contains all information about the created OpenStack
            Network. It includes Subnets and Router.
          properties:
            id:
              type: string
            name:
              type: string
            router:
              properties:
                id:
                  type: string
                name:
                  type: string
              required:
              - name
              - id
              type: object
            subnet:
              properties:
                cidr:
                  type: string
                id:
                  type: string
                name:
                  type: string
              required:
              - name
              - id
              - cidr
              type: object
          required:
          - name
          - id
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
