apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: cloud-config
  files:
    - clouds.yaml=configs/clouds.yaml
    - cacert=configs/cacert
  type: Opaque
- name: cloud-selector
  files:
    - OS_CLOUD=configs/os_cloud.txt
  type: Opaque

namespace: capo-system
