---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha7-openstackcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.openstackcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha7
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclusters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha7-openstackclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.openstackclustertemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha7
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha7-openstackmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.openstackmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha7
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackmachines
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha7-openstackmachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.openstackmachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha7
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackmachinetemplates
  sideEffects: None
