---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: openstackproviderspecs.openstackproviderconfig.k8s.io
spec:
  group: openstackproviderconfig.k8s.io
  names:
    kind: OpenstackProviderSpec
    plural: openstackproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        name:
          type: string
        flavor:
          type: string
        image:
          type: string
        networks:
          items:
            uuid:
              type: string
            fixed_ip:
              type: string
            filter:
              type: object
          type: array
        floatingIP:
          type: string
        availabilityZone:
          type: string
        securityGroups:
          items:
            type: string
          type: array
        root_volume:
          properties:
            volumeType:
              type: string
            diskSize:
              type: string
          type: object
        metadata:
          type: object
      required:
        - name
        - flavor
        - image
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
