name: Update golangci-lint version

on:
  schedule:
  - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:
    # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-golangci-lint:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get_version.outputs.latest_version }}
      current_version: ${{ steps.check_version.outputs.current_version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
    - name: Get latest golangci-lint version
      id: get_version
      run: |
        export LATEST_VERSION=$(curl -s https://api.github.com/repos/golangci/golangci-lint/releases/latest | jq -r .tag_name)
        echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
        echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_OUTPUT
    - name: Check current version in Makefile
      id: check_version
      run: |
        export CURRENT_VERSION=$(grep 'GOLANGCI_LINT_VERSION ?=' hack/tools/Makefile | cut -d '=' -f2 | tr -d ' ')
        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
    - name: Update Makefile if needed
      if: ${{ steps.check_version.outputs.current_version != steps.get_version.outputs.latest_version }}
      run: |
        sed -i "s/GOLANGCI_LINT_VERSION ?= .*/GOLANGCI_LINT_VERSION ?= ${{ steps.get_version.outputs.latest_version }}/" hack/tools/Makefile
    - name: Create Pull Request
      if: ${{ steps.check_version.outputs.current_version != steps.get_version.outputs.latest_version }}
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # tag=v7.0.11
      with:
        commit-message: "This commit updates golangci-lint to version v${{ steps.get_version.outputs.latest_version }}."
        title: ":seedling: chore: bump golangci-lint to v${{ steps.get_version.outputs.latest_version }}"
        body: |
          This PR was generated by GH workflow `update-golangci-lint` and
          updates golangci-lint to version v${{ steps.get_version.outputs.latest_version }}.
        branch: update-golangci-lint-${{ steps.get_version.outputs.latest_version }}
        base: main
        labels: "area/dependency"
        add-paths: |
          hack/tools/Makefile
